apiVersion: v1
name: elasticsearch
home: https://www.elastic.co/products/elasticsearch
version: 0.2.2
description: Elasticsearch cluster with 3 master nodes 2 data nodes and 2 client nodes
icon: https://static-www.elastic.co/assets/blteb1c97719574938d/logo-elastic-elasticsearch-lt.svg
sources:
  - https://www.elastic.co/products/elasticsearch
  - https://github.com/pires/kubernetes-elasticsearch-cluster
maintainers:
  - name: Matt Titmus
    email: matthew.titmus@gmail.com
engine: gotpl
